/*
================================================================================
SQL-ONLY DECLINE OPPORTUNITY SOLUTION
================================================================================
Purpose:
  This script is for Snowflake environments where SNOWFLAKE.ML.CLASSIFICATION
  privilege is not available.

Business Scope:
  - Exclude NTU completely.
  - Use only Declined and Signed & Bound records.
  - Produce two outputs:
      1) ML_DECLINE_OPPORTUNITY_REVIEW_SQL_ONLY
         -> Declined cases ranked by similarity to historically Signed & Bound cases.
      2) ML_DECLINE_DRIVER_SUMMARY_SQL_ONLY
         -> Variables / values most associated with Decline.

Input table expected:
  ML_DATA_PHASE1

Main output tables:
  ML_DECLINE_SIGNED_BASE
  ML_DECLINE_DRIVER_SUMMARY_SQL_ONLY
  ML_FEATURE_SIGNED_BOUND_RATES
  ML_DECLINE_OPPORTUNITY_REVIEW_SQL_ONLY

How this works:
  - For each feature value, calculate historical Signed & Bound rate and Decline rate.
  - For each declined submission, compare its feature values against historical
    Signed & Bound rates.
  - Average those feature-level Signed & Bound rates to create a similarity score.
  - Apply a business-rule adjustment layer to create FINAL_OPPORTUNITY_SCORE.

Important:
  - This is not a formal Snowflake ML model.
  - It is a SQL-only statistical/business scoring approach.
  - It is useful until CREATE SNOWFLAKE.ML.CLASSIFICATION privilege is granted.
================================================================================
*/

/*===============================================================================
0. OPTIONAL: SET CONTEXT
===============================================================================*/

-- Update these if required in your environment.
USE ROLE EXPERIMENT_TEAM_FULL;
USE DATABASE EXPERIMENT_TEAM_DB;
USE SCHEMA PUBLIC;


/*===============================================================================
1. CREATE BASE TABLE: ONLY DECLINED + SIGNED & BOUND
===============================================================================*/

CREATE OR REPLACE TABLE ML_DECLINE_SIGNED_BASE AS
SELECT
    *,
    CASE
        WHEN UWRISK_INWARDINSUREDLINE_LINESTATUS = 'Signed & Bound' THEN 1
        WHEN UWRISK_INWARDINSUREDLINE_LINESTATUS = 'Declined' THEN 0
    END AS SIGNED_BOUND_TARGET
FROM ML_DATA_PHASE1
WHERE UWRISK_INWARDINSUREDLINE_LINESTATUS IN ('Declined', 'Signed & Bound');


/*===============================================================================
2. BASIC CLASS BALANCE CHECK
===============================================================================*/

SELECT
    UWRISK_INWARDINSUREDLINE_LINESTATUS AS LINE_STATUS,
    COUNT(*) AS RECORD_COUNT,
    ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 2) AS PERCENTAGE
FROM ML_DECLINE_SIGNED_BASE
GROUP BY UWRISK_INWARDINSUREDLINE_LINESTATUS
ORDER BY RECORD_COUNT DESC;


/*===============================================================================
3. DRIVER SUMMARY: WHICH FEATURE VALUES HAVE HIGH DECLINE RATE?
===============================================================================*/

CREATE OR REPLACE TABLE ML_DECLINE_DRIVER_SUMMARY_SQL_ONLY AS
SELECT
    FEATURE_NAME,
    FEATURE_VALUE,
    COUNT(*) AS TOTAL_RECORDS,
    SUM(CASE WHEN UWRISK_INWARDINSUREDLINE_LINESTATUS = 'Declined' THEN 1 ELSE 0 END) AS DECLINED_COUNT,
    SUM(CASE WHEN UWRISK_INWARDINSUREDLINE_LINESTATUS = 'Signed & Bound' THEN 1 ELSE 0 END) AS SIGNED_BOUND_COUNT,
    ROUND(
        100.0 * SUM(CASE WHEN UWRISK_INWARDINSUREDLINE_LINESTATUS = 'Declined' THEN 1 ELSE 0 END)
        / NULLIF(COUNT(*), 0),
        2
    ) AS DECLINE_RATE_PERCENT,
    ROUND(
        100.0 * SUM(CASE WHEN UWRISK_INWARDINSUREDLINE_LINESTATUS = 'Signed & Bound' THEN 1 ELSE 0 END)
        / NULLIF(COUNT(*), 0),
        2
    ) AS SIGNED_BOUND_RATE_PERCENT
FROM (
    /* Core segmentation */
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'NEW_OR_RENEWAL' AS FEATURE_NAME, UWRISK_INWARDSUBMISSION_NEWORRENEWAL AS FEATURE_VALUE FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'BROKER_NAME', UWRISK_INWARDSUBMISSION_BROKERNAME FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'PLACING_BASIS', UWRISK_INWARDRISKSECTION_PLACINGBASIS FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'ACTIVITY_SEGMENT', UWRISK_INWARDSUBMISSION_ACTIVITY1SEGMENT FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'CLASS_OF_BUSINESS_TIER2', UWRISK_INWARDRISKSECTION_CLASSOFBUSINESSTIER2NAME FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'TARGET_MARKET', UWRISK_INWARDRISKSECTION_TARGETMARKET FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'PREDOMINANT_EXPOSURE_REGION', OED_UWRISK_PREDOMINANTEXPOSUREREGION FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'EXPOSURE_REGION_GROUP', EXPOSURE_REGION_GROUP FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'TOTALTIV_BAND', TOTALTIV_BAND FROM ML_DECLINE_SIGNED_BASE

    /* UW flags */
    UNION ALL
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'UWRISK_FAVOCCUPANCYFLAG', UWRISK_FAVOCCUPANCYFLAG::VARCHAR FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'UWRISK_HEAVYOCCUPANCYFLAG', UWRISK_HEAVYOCCUPANCYFLAG::VARCHAR FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'UWRISK_POORAPPRAISALVALUESFLAG', UWRISK_POORAPPRAISALVALUESFLAG::VARCHAR FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'UWRISK_BROKERCHURNFLAG', UWRISK_BROKERCHURNFLAG::VARCHAR FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'UWRISK_FLUCTUATINGTIVFLAG', UWRISK_FLUCTUATINGTIVFLAG::VARCHAR FROM ML_DECLINE_SIGNED_BASE

    /* Exposure / concentration */
    UNION ALL
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'OED_SINGLESITEDOMINANCECATEGORY', OED_SINGLESITEDOMINANCECATEGORY FROM ML_DECLINE_SIGNED_BASE

    /* Construction */
    UNION ALL
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'OED_DOMINANT_CONSTRUCTION_CLASS', OED_DOMINANT_CONSTRUCTION_CLASS FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'OED_DOMINANT_ISO_CONSTRUCTION_CODE', OED_DOMINANT_ISO_CONSTRUCTION_CODE FROM ML_DECLINE_SIGNED_BASE

    /* Occupancy */
    UNION ALL
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'OED_DOMINANT_OCCUPANCY_CLASS', OED_DOMINANT_OCCUPANCY_CLASS FROM ML_DECLINE_SIGNED_BASE

    /* Roof / hazard */
    UNION ALL
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'OED_DOMINANT_ROOF_ANCHORAGE', OED_DOMINANT_ROOF_ANCHORAGE FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'OED_DOMINANT_ROOF_ANCHORAGE_RISK_CATEGORY', OED_DOMINANT_ROOF_ANCHORAGE_RISK_CATEGORY FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'EXT_FL_HIGHESTRISKCATEGORY', EXT_FL_HIGHESTRISKCATEGORY FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'EXT_WS_HIGHESTRISKCATEGORY', EXT_WS_HIGHESTRISKCATEGORY FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'EXT_EQ_HIGHESTRISKCATEGORY', EXT_EQ_HIGHESTRISKCATEGORY FROM ML_DECLINE_SIGNED_BASE

    /* Protection flags */
    UNION ALL
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'OED_PROTECTION_DOMINANTLOC_NOSPRINKLR', OED_PROTECTION_DOMINANTLOC_NOSPRINKLR::VARCHAR FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'AI_PROTECTION_SPRIKLERTYPE_PREACTIONFLAG', AI_PROTECTION_SPRIKLERTYPE_PREACTIONFLAG::VARCHAR FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'AI_PROTECTION_SPRIKLERTYPE_DELUGEFLAG', AI_PROTECTION_SPRIKLERTYPE_DELUGEFLAG::VARCHAR FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'AI_PROTECTION_FIREALARMTYPE_ANYCENTRALSTATIONFLAG', AI_PROTECTION_FIREALARMTYPE_ANYCENTRALSTATIONFLAG::VARCHAR FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'AI_PROTECTION_FIREALARMTYPE_ANYLOCALALARMFLAG', AI_PROTECTION_FIREALARMTYPE_ANYLOCALALARMFLAG::VARCHAR FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'AI_PROTECTION_PPCODE_ANYPREFERREDFLAG', AI_PROTECTION_PPCODE_ANYPREFERREDFLAG::VARCHAR FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'AI_PROTECTION_PPCODE_ANYSTANDARDFLAG', AI_PROTECTION_PPCODE_ANYSTANDARDFLAG::VARCHAR FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'AI_PROTECTION_PPCODE_ANYRESTRICTEDFLAG', AI_PROTECTION_PPCODE_ANYRESTRICTEDFLAG::VARCHAR FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'AI_PROTECTION_EQRESISTIVESYSTEM_ANYFLAG', AI_PROTECTION_EQRESISTIVESYSTEM_ANYFLAG::VARCHAR FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'AI_PROTECTION_ROOFMATERIAL_ANYHIGHPROTECTIONFLAG', AI_PROTECTION_ROOFMATERIAL_ANYHIGHPROTECTIONFLAG::VARCHAR FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'AI_PROTECTION_ROOFMATERIAL_ANYLOWPROTECTIONFLAG', AI_PROTECTION_ROOFMATERIAL_ANYLOWPROTECTIONFLAG::VARCHAR FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'AI_PROTECTION_ROOFANCHORAGE_ANYHIGHPROTECTIONFLAG', AI_PROTECTION_ROOFANCHORAGE_ANYHIGHPROTECTIONFLAG::VARCHAR FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'AI_PROTECTION_ROOFANCHORAGE_ANYLOWPROTECTIONFLAG', AI_PROTECTION_ROOFANCHORAGE_ANYLOWPROTECTIONFLAG::VARCHAR FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'DERIVED_WOODFRAME_RESTRICTEDPPC_FLAG', DERIVED_WOODFRAME_RESTRICTEDPPC_FLAG::VARCHAR FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'DERIVED_WOODFRAME_NOSPRINKLER_FLAG', DERIVED_WOODFRAME_NOSPRINKLER_FLAG::VARCHAR FROM ML_DECLINE_SIGNED_BASE

    /* Loss history */
    UNION ALL
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'LAST5YEARS_NUMBEROFCLAIMSBAND', LAST5YEARS_NUMBEROFCLAIMSBAND FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'LAST10YEARS_NUMBEROFCLAIMSBAND', LAST10YEARS_NUMBEROFCLAIMSBAND FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT UWRISK_INWARDINSUREDLINE_LINESTATUS, 'PORTFOLIO_BURNING_COST_LAST5YEARS_BANDS', PORTFOLIO_BURNING_COST_LAST5YEARS_BANDS FROM ML_DECLINE_SIGNED_BASE
)
WHERE FEATURE_VALUE IS NOT NULL
GROUP BY FEATURE_NAME, FEATURE_VALUE
HAVING COUNT(*) >= 5
ORDER BY DECLINE_RATE_PERCENT DESC, TOTAL_RECORDS DESC;


/*===============================================================================
4. VIEW TOP DECLINE DRIVERS
===============================================================================*/

SELECT *
FROM ML_DECLINE_DRIVER_SUMMARY_SQL_ONLY
WHERE TOTAL_RECORDS >= 10
ORDER BY DECLINE_RATE_PERCENT DESC, TOTAL_RECORDS DESC;


/*===============================================================================
5. CREATE FEATURE-LEVEL SIGNED & BOUND RATES
===============================================================================*/

CREATE OR REPLACE TABLE ML_FEATURE_SIGNED_BOUND_RATES AS
SELECT
    FEATURE_NAME,
    FEATURE_VALUE,
    COUNT(*) AS TOTAL_RECORDS,
    AVG(SIGNED_BOUND_TARGET) AS SIGNED_BOUND_RATE,
    ROUND(100 * AVG(SIGNED_BOUND_TARGET), 2) AS SIGNED_BOUND_RATE_PERCENT
FROM (
    /* Core segmentation */
    SELECT SIGNED_BOUND_TARGET, 'NEW_OR_RENEWAL' AS FEATURE_NAME, UWRISK_INWARDSUBMISSION_NEWORRENEWAL AS FEATURE_VALUE FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT SIGNED_BOUND_TARGET, 'BROKER_NAME', UWRISK_INWARDSUBMISSION_BROKERNAME FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT SIGNED_BOUND_TARGET, 'PLACING_BASIS', UWRISK_INWARDRISKSECTION_PLACINGBASIS FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT SIGNED_BOUND_TARGET, 'ACTIVITY_SEGMENT', UWRISK_INWARDSUBMISSION_ACTIVITY1SEGMENT FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT SIGNED_BOUND_TARGET, 'CLASS_OF_BUSINESS_TIER2', UWRISK_INWARDRISKSECTION_CLASSOFBUSINESSTIER2NAME FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT SIGNED_BOUND_TARGET, 'TARGET_MARKET', UWRISK_INWARDRISKSECTION_TARGETMARKET FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT SIGNED_BOUND_TARGET, 'PREDOMINANT_EXPOSURE_REGION', OED_UWRISK_PREDOMINANTEXPOSUREREGION FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT SIGNED_BOUND_TARGET, 'EXPOSURE_REGION_GROUP', EXPOSURE_REGION_GROUP FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT SIGNED_BOUND_TARGET, 'TOTALTIV_BAND', TOTALTIV_BAND FROM ML_DECLINE_SIGNED_BASE

    /* UW flags */
    UNION ALL
    SELECT SIGNED_BOUND_TARGET, 'UWRISK_FAVOCCUPANCYFLAG', UWRISK_FAVOCCUPANCYFLAG::VARCHAR FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT SIGNED_BOUND_TARGET, 'UWRISK_HEAVYOCCUPANCYFLAG', UWRISK_HEAVYOCCUPANCYFLAG::VARCHAR FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT SIGNED_BOUND_TARGET, 'UWRISK_POORAPPRAISALVALUESFLAG', UWRISK_POORAPPRAISALVALUESFLAG::VARCHAR FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT SIGNED_BOUND_TARGET, 'UWRISK_BROKERCHURNFLAG', UWRISK_BROKERCHURNFLAG::VARCHAR FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT SIGNED_BOUND_TARGET, 'UWRISK_FLUCTUATINGTIVFLAG', UWRISK_FLUCTUATINGTIVFLAG::VARCHAR FROM ML_DECLINE_SIGNED_BASE

    /* Exposure / construction / occupancy / hazard */
    UNION ALL
    SELECT SIGNED_BOUND_TARGET, 'OED_SINGLESITEDOMINANCECATEGORY', OED_SINGLESITEDOMINANCECATEGORY FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT SIGNED_BOUND_TARGET, 'OED_DOMINANT_CONSTRUCTION_CLASS', OED_DOMINANT_CONSTRUCTION_CLASS FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT SIGNED_BOUND_TARGET, 'OED_DOMINANT_ISO_CONSTRUCTION_CODE', OED_DOMINANT_ISO_CONSTRUCTION_CODE FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT SIGNED_BOUND_TARGET, 'OED_DOMINANT_OCCUPANCY_CLASS', OED_DOMINANT_OCCUPANCY_CLASS FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT SIGNED_BOUND_TARGET, 'OED_DOMINANT_ROOF_ANCHORAGE_RISK_CATEGORY', OED_DOMINANT_ROOF_ANCHORAGE_RISK_CATEGORY FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT SIGNED_BOUND_TARGET, 'EXT_FL_HIGHESTRISKCATEGORY', EXT_FL_HIGHESTRISKCATEGORY FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT SIGNED_BOUND_TARGET, 'EXT_WS_HIGHESTRISKCATEGORY', EXT_WS_HIGHESTRISKCATEGORY FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT SIGNED_BOUND_TARGET, 'EXT_EQ_HIGHESTRISKCATEGORY', EXT_EQ_HIGHESTRISKCATEGORY FROM ML_DECLINE_SIGNED_BASE

    /* Protection */
    UNION ALL
    SELECT SIGNED_BOUND_TARGET, 'OED_PROTECTION_DOMINANTLOC_NOSPRINKLR', OED_PROTECTION_DOMINANTLOC_NOSPRINKLR::VARCHAR FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT SIGNED_BOUND_TARGET, 'AI_PROTECTION_PPCODE_ANYRESTRICTEDFLAG', AI_PROTECTION_PPCODE_ANYRESTRICTEDFLAG::VARCHAR FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT SIGNED_BOUND_TARGET, 'DERIVED_WOODFRAME_RESTRICTEDPPC_FLAG', DERIVED_WOODFRAME_RESTRICTEDPPC_FLAG::VARCHAR FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT SIGNED_BOUND_TARGET, 'DERIVED_WOODFRAME_NOSPRINKLER_FLAG', DERIVED_WOODFRAME_NOSPRINKLER_FLAG::VARCHAR FROM ML_DECLINE_SIGNED_BASE

    /* Loss history */
    UNION ALL
    SELECT SIGNED_BOUND_TARGET, 'LAST5YEARS_NUMBEROFCLAIMSBAND', LAST5YEARS_NUMBEROFCLAIMSBAND FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT SIGNED_BOUND_TARGET, 'LAST10YEARS_NUMBEROFCLAIMSBAND', LAST10YEARS_NUMBEROFCLAIMSBAND FROM ML_DECLINE_SIGNED_BASE
    UNION ALL
    SELECT SIGNED_BOUND_TARGET, 'PORTFOLIO_BURNING_COST_LAST5YEARS_BANDS', PORTFOLIO_BURNING_COST_LAST5YEARS_BANDS FROM ML_DECLINE_SIGNED_BASE
)
WHERE FEATURE_VALUE IS NOT NULL
GROUP BY FEATURE_NAME, FEATURE_VALUE
HAVING COUNT(*) >= 5;


/*===============================================================================
6. CREATE SQL-ONLY OPPORTUNITY REVIEW TABLE FOR DECLINED CASES
===============================================================================*/

CREATE OR REPLACE TABLE ML_DECLINE_OPPORTUNITY_REVIEW_SQL_ONLY AS
WITH GLOBAL_RATE AS (
    SELECT AVG(SIGNED_BOUND_TARGET) AS GLOBAL_SIGNED_BOUND_RATE
    FROM ML_DECLINE_SIGNED_BASE
),
DECLINED_FEATURES AS (
    SELECT
        UWRISK_INWARDSUBMISSION_CONVEXSUBMISSIONREFERENCE AS SUBMISSION_REFERENCE,
        UWRISK_INWARDINSUREDLINE_LINESTATUS AS LINE_STATUS,
        UWRISK_INWARDSUBMISSION_BROKERNAME AS BROKER_NAME,
        UWRISK_INWARDSUBMISSION_NEWORRENEWAL AS NEW_OR_RENEWAL,
        UWRISK_INWARDRISKSECTION_TARGETMARKET AS TARGET_MARKET,
        OED_UWRISK_PREDOMINANTEXPOSUREREGION AS PREDOMINANT_EXPOSURE_REGION,
        EXPOSURE_REGION_GROUP,
        TOTALTIV_BAND,
        OED_DOMINANT_OCCUPANCY_CLASS,
        OED_DOMINANT_CONSTRUCTION_CLASS,
        OED_DOMINANT_ISO_CONSTRUCTION_CODE,
        UWRISK_FAVOCCUPANCYFLAG,
        UWRISK_HEAVYOCCUPANCYFLAG,
        UWRISK_POORAPPRAISALVALUESFLAG,
        UWRISK_BROKERCHURNFLAG,
        UWRISK_FLUCTUATINGTIVFLAG,
        EXT_FL_HIGHESTRISKCATEGORY,
        EXT_WS_HIGHESTRISKCATEGORY,
        EXT_EQ_HIGHESTRISKCATEGORY,
        LAST5YEARS_NUMBEROFCLAIMSBAND,
        LAST10YEARS_NUMBEROFCLAIMSBAND,
        PORTFOLIO_BURNING_COST_LAST5YEARS_BANDS,
        FEATURE_NAME,
        FEATURE_VALUE
    FROM (
        SELECT *, 'NEW_OR_RENEWAL' AS FEATURE_NAME, UWRISK_INWARDSUBMISSION_NEWORRENEWAL AS FEATURE_VALUE FROM ML_DECLINE_SIGNED_BASE
        UNION ALL
        SELECT *, 'BROKER_NAME', UWRISK_INWARDSUBMISSION_BROKERNAME FROM ML_DECLINE_SIGNED_BASE
        UNION ALL
        SELECT *, 'TARGET_MARKET', UWRISK_INWARDRISKSECTION_TARGETMARKET FROM ML_DECLINE_SIGNED_BASE
        UNION ALL
        SELECT *, 'EXPOSURE_REGION_GROUP', EXPOSURE_REGION_GROUP FROM ML_DECLINE_SIGNED_BASE
        UNION ALL
        SELECT *, 'TOTALTIV_BAND', TOTALTIV_BAND FROM ML_DECLINE_SIGNED_BASE
        UNION ALL
        SELECT *, 'OED_DOMINANT_OCCUPANCY_CLASS', OED_DOMINANT_OCCUPANCY_CLASS FROM ML_DECLINE_SIGNED_BASE
        UNION ALL
        SELECT *, 'OED_DOMINANT_CONSTRUCTION_CLASS', OED_DOMINANT_CONSTRUCTION_CLASS FROM ML_DECLINE_SIGNED_BASE
        UNION ALL
        SELECT *, 'OED_DOMINANT_ISO_CONSTRUCTION_CODE', OED_DOMINANT_ISO_CONSTRUCTION_CODE FROM ML_DECLINE_SIGNED_BASE
        UNION ALL
        SELECT *, 'EXT_FL_HIGHESTRISKCATEGORY', EXT_FL_HIGHESTRISKCATEGORY FROM ML_DECLINE_SIGNED_BASE
        UNION ALL
        SELECT *, 'EXT_WS_HIGHESTRISKCATEGORY', EXT_WS_HIGHESTRISKCATEGORY FROM ML_DECLINE_SIGNED_BASE
        UNION ALL
        SELECT *, 'EXT_EQ_HIGHESTRISKCATEGORY', EXT_EQ_HIGHESTRISKCATEGORY FROM ML_DECLINE_SIGNED_BASE
        UNION ALL
        SELECT *, 'LAST5YEARS_NUMBEROFCLAIMSBAND', LAST5YEARS_NUMBEROFCLAIMSBAND FROM ML_DECLINE_SIGNED_BASE
        UNION ALL
        SELECT *, 'LAST10YEARS_NUMBEROFCLAIMSBAND', LAST10YEARS_NUMBEROFCLAIMSBAND FROM ML_DECLINE_SIGNED_BASE
        UNION ALL
        SELECT *, 'PORTFOLIO_BURNING_COST_LAST5YEARS_BANDS', PORTFOLIO_BURNING_COST_LAST5YEARS_BANDS FROM ML_DECLINE_SIGNED_BASE
        UNION ALL
        SELECT *, 'UWRISK_FAVOCCUPANCYFLAG', UWRISK_FAVOCCUPANCYFLAG::VARCHAR FROM ML_DECLINE_SIGNED_BASE
        UNION ALL
        SELECT *, 'UWRISK_HEAVYOCCUPANCYFLAG', UWRISK_HEAVYOCCUPANCYFLAG::VARCHAR FROM ML_DECLINE_SIGNED_BASE
        UNION ALL
        SELECT *, 'UWRISK_POORAPPRAISALVALUESFLAG', UWRISK_POORAPPRAISALVALUESFLAG::VARCHAR FROM ML_DECLINE_SIGNED_BASE
        UNION ALL
        SELECT *, 'UWRISK_BROKERCHURNFLAG', UWRISK_BROKERCHURNFLAG::VARCHAR FROM ML_DECLINE_SIGNED_BASE
        UNION ALL
        SELECT *, 'UWRISK_FLUCTUATINGTIVFLAG', UWRISK_FLUCTUATINGTIVFLAG::VARCHAR FROM ML_DECLINE_SIGNED_BASE
        UNION ALL
        SELECT *, 'OED_PROTECTION_DOMINANTLOC_NOSPRINKLR', OED_PROTECTION_DOMINANTLOC_NOSPRINKLR::VARCHAR FROM ML_DECLINE_SIGNED_BASE
        UNION ALL
        SELECT *, 'AI_PROTECTION_PPCODE_ANYRESTRICTEDFLAG', AI_PROTECTION_PPCODE_ANYRESTRICTEDFLAG::VARCHAR FROM ML_DECLINE_SIGNED_BASE
        UNION ALL
        SELECT *, 'DERIVED_WOODFRAME_RESTRICTEDPPC_FLAG', DERIVED_WOODFRAME_RESTRICTEDPPC_FLAG::VARCHAR FROM ML_DECLINE_SIGNED_BASE
        UNION ALL
        SELECT *, 'DERIVED_WOODFRAME_NOSPRINKLER_FLAG', DERIVED_WOODFRAME_NOSPRINKLER_FLAG::VARCHAR FROM ML_DECLINE_SIGNED_BASE
    )
    WHERE UWRISK_INWARDINSUREDLINE_LINESTATUS = 'Declined'
      AND FEATURE_VALUE IS NOT NULL
),
SCORED_FEATURES AS (
    SELECT
        d.*,
        COALESCE(r.SIGNED_BOUND_RATE, g.GLOBAL_SIGNED_BOUND_RATE) AS FEATURE_SIGNED_BOUND_RATE
    FROM DECLINED_FEATURES d
    CROSS JOIN GLOBAL_RATE g
    LEFT JOIN ML_FEATURE_SIGNED_BOUND_RATES r
        ON d.FEATURE_NAME = r.FEATURE_NAME
       AND d.FEATURE_VALUE = r.FEATURE_VALUE
),
AGG AS (
    SELECT
        SUBMISSION_REFERENCE,
        MAX(LINE_STATUS) AS LINE_STATUS,
        MAX(BROKER_NAME) AS BROKER_NAME,
        MAX(NEW_OR_RENEWAL) AS NEW_OR_RENEWAL,
        MAX(TARGET_MARKET) AS TARGET_MARKET,
        MAX(PREDOMINANT_EXPOSURE_REGION) AS PREDOMINANT_EXPOSURE_REGION,
        MAX(EXPOSURE_REGION_GROUP) AS EXPOSURE_REGION_GROUP,
        MAX(TOTALTIV_BAND) AS TOTALTIV_BAND,
        MAX(OED_DOMINANT_OCCUPANCY_CLASS) AS OED_DOMINANT_OCCUPANCY_CLASS,
        MAX(OED_DOMINANT_CONSTRUCTION_CLASS) AS OED_DOMINANT_CONSTRUCTION_CLASS,
        MAX(OED_DOMINANT_ISO_CONSTRUCTION_CODE) AS OED_DOMINANT_ISO_CONSTRUCTION_CODE,
        MAX(UWRISK_FAVOCCUPANCYFLAG) AS UWRISK_FAVOCCUPANCYFLAG,
        MAX(UWRISK_HEAVYOCCUPANCYFLAG) AS UWRISK_HEAVYOCCUPANCYFLAG,
        MAX(UWRISK_POORAPPRAISALVALUESFLAG) AS UWRISK_POORAPPRAISALVALUESFLAG,
        MAX(UWRISK_BROKERCHURNFLAG) AS UWRISK_BROKERCHURNFLAG,
        MAX(UWRISK_FLUCTUATINGTIVFLAG) AS UWRISK_FLUCTUATINGTIVFLAG,
        MAX(EXT_FL_HIGHESTRISKCATEGORY) AS EXT_FL_HIGHESTRISKCATEGORY,
        MAX(EXT_WS_HIGHESTRISKCATEGORY) AS EXT_WS_HIGHESTRISKCATEGORY,
        MAX(EXT_EQ_HIGHESTRISKCATEGORY) AS EXT_EQ_HIGHESTRISKCATEGORY,
        MAX(LAST5YEARS_NUMBEROFCLAIMSBAND) AS LAST5YEARS_NUMBEROFCLAIMSBAND,
        MAX(LAST10YEARS_NUMBEROFCLAIMSBAND) AS LAST10YEARS_NUMBEROFCLAIMSBAND,
        MAX(PORTFOLIO_BURNING_COST_LAST5YEARS_BANDS) AS PORTFOLIO_BURNING_COST_LAST5YEARS_BANDS,

        AVG(FEATURE_SIGNED_BOUND_RATE) AS SQL_SIGNED_BOUND_SIMILARITY_SCORE,

        LISTAGG(
            FEATURE_NAME || '=' || FEATURE_VALUE || ' signed_bound_rate=' || ROUND(FEATURE_SIGNED_BOUND_RATE, 2),
            '; '
        ) WITHIN GROUP (ORDER BY FEATURE_SIGNED_BOUND_RATE DESC) AS FEATURE_EVIDENCE
    FROM SCORED_FEATURES
    GROUP BY SUBMISSION_REFERENCE
),
FINAL AS (
    SELECT
        *,
        LEAST(
            1,
            GREATEST(
                0,
                SQL_SIGNED_BOUND_SIMILARITY_SCORE
                + CASE WHEN COALESCE(UWRISK_FAVOCCUPANCYFLAG, 0) = 1 THEN 0.05 ELSE 0 END
                + CASE WHEN LOWER(NEW_OR_RENEWAL) = 'renewal' THEN 0.05 ELSE 0 END
                - CASE WHEN COALESCE(UWRISK_POORAPPRAISALVALUESFLAG, 0) = 1 THEN 0.15 ELSE 0 END
                - CASE WHEN COALESCE(UWRISK_HEAVYOCCUPANCYFLAG, 0) = 1 THEN 0.10 ELSE 0 END
                - CASE WHEN COALESCE(UWRISK_BROKERCHURNFLAG, 0) = 1 THEN 0.05 ELSE 0 END
                - CASE WHEN COALESCE(UWRISK_FLUCTUATINGTIVFLAG, 0) = 1 THEN 0.05 ELSE 0 END
                - CASE WHEN EXT_FL_HIGHESTRISKCATEGORY = 'High Risk Category' THEN 0.05 ELSE 0 END
                - CASE WHEN EXT_WS_HIGHESTRISKCATEGORY = 'High Risk Category' THEN 0.05 ELSE 0 END
                - CASE WHEN EXT_EQ_HIGHESTRISKCATEGORY = 'High Risk Category' THEN 0.05 ELSE 0 END
            )
        ) AS FINAL_OPPORTUNITY_SCORE
    FROM AGG
)
SELECT
    *,
    CASE
        WHEN FINAL_OPPORTUNITY_SCORE >= 0.70 THEN 'High Review Priority'
        WHEN FINAL_OPPORTUNITY_SCORE >= 0.40 THEN 'Medium Review Priority'
        ELSE 'Low Review Priority'
    END AS REVIEW_PRIORITY,
    CONCAT_WS(
        '; ',
        CASE WHEN COALESCE(UWRISK_FAVOCCUPANCYFLAG, 0) = 1 THEN 'Positive: favourable occupancy flag' END,
        CASE WHEN LOWER(NEW_OR_RENEWAL) = 'renewal' THEN 'Positive: renewal business' END,
        CASE WHEN COALESCE(UWRISK_POORAPPRAISALVALUESFLAG, 0) = 1 THEN 'Negative: poor appraisal values flag' END,
        CASE WHEN COALESCE(UWRISK_HEAVYOCCUPANCYFLAG, 0) = 1 THEN 'Negative: heavy occupancy flag' END,
        CASE WHEN COALESCE(UWRISK_BROKERCHURNFLAG, 0) = 1 THEN 'Negative: broker churn flag' END,
        CASE WHEN COALESCE(UWRISK_FLUCTUATINGTIVFLAG, 0) = 1 THEN 'Negative: fluctuating TIV flag' END,
        CASE WHEN EXT_FL_HIGHESTRISKCATEGORY = 'High Risk Category' THEN 'Negative: high flood risk category' END,
        CASE WHEN EXT_WS_HIGHESTRISKCATEGORY = 'High Risk Category' THEN 'Negative: high windstorm risk category' END,
        CASE WHEN EXT_EQ_HIGHESTRISKCATEGORY = 'High Risk Category' THEN 'Negative: high earthquake risk category' END
    ) AS BUSINESS_RULE_EVIDENCE
FROM FINAL;


/*===============================================================================
7. VIEW FINAL OPPORTUNITY OUTPUT
===============================================================================*/

SELECT
    SUBMISSION_REFERENCE,
    BROKER_NAME,
    NEW_OR_RENEWAL,
    TARGET_MARKET,
    EXPOSURE_REGION_GROUP,
    TOTALTIV_BAND,
    SQL_SIGNED_BOUND_SIMILARITY_SCORE,
    FINAL_OPPORTUNITY_SCORE,
    REVIEW_PRIORITY,
    BUSINESS_RULE_EVIDENCE,
    FEATURE_EVIDENCE
FROM ML_DECLINE_OPPORTUNITY_REVIEW_SQL_ONLY
ORDER BY FINAL_OPPORTUNITY_SCORE DESC;


/*===============================================================================
8. OPTIONAL SUMMARY COUNTS BY REVIEW PRIORITY
===============================================================================*/

SELECT
    REVIEW_PRIORITY,
    COUNT(*) AS RECORD_COUNT,
    ROUND(AVG(FINAL_OPPORTUNITY_SCORE), 3) AS AVG_FINAL_OPPORTUNITY_SCORE,
    ROUND(MIN(FINAL_OPPORTUNITY_SCORE), 3) AS MIN_FINAL_OPPORTUNITY_SCORE,
    ROUND(MAX(FINAL_OPPORTUNITY_SCORE), 3) AS MAX_FINAL_OPPORTUNITY_SCORE
FROM ML_DECLINE_OPPORTUNITY_REVIEW_SQL_ONLY
GROUP BY REVIEW_PRIORITY
ORDER BY AVG_FINAL_OPPORTUNITY_SCORE DESC;


/*===============================================================================
9. OPTIONAL: TOP HIGH-PRIORITY DECLINED CASES
===============================================================================*/

SELECT
    SUBMISSION_REFERENCE,
    BROKER_NAME,
    NEW_OR_RENEWAL,
    TARGET_MARKET,
    PREDOMINANT_EXPOSURE_REGION,
    EXPOSURE_REGION_GROUP,
    TOTALTIV_BAND,
    OED_DOMINANT_OCCUPANCY_CLASS,
    OED_DOMINANT_CONSTRUCTION_CLASS,
    SQL_SIGNED_BOUND_SIMILARITY_SCORE,
    FINAL_OPPORTUNITY_SCORE,
    REVIEW_PRIORITY,
    BUSINESS_RULE_EVIDENCE
FROM ML_DECLINE_OPPORTUNITY_REVIEW_SQL_ONLY
WHERE REVIEW_PRIORITY = 'High Review Priority'
ORDER BY FINAL_OPPORTUNITY_SCORE DESC;


/*===============================================================================
10. BUSINESS NOTES
===============================================================================
How to explain:

1. We filtered the data to only Declined and Signed & Bound records.
2. For each feature value, we calculated historical Signed & Bound rate and
   Decline rate.
3. For each declined submission, we calculated how strongly its feature values
   resemble values that historically ended as Signed & Bound.
4. The SQL_SIGNED_BOUND_SIMILARITY_SCORE is the average historical signed-bound
   rate of the declined record's feature values.
5. FINAL_OPPORTUNITY_SCORE applies a business-rule adjustment layer:
      - Positive adjustment for favourable occupancy and renewal business.
      - Negative adjustment for poor appraisal, heavy occupancy, broker churn,
        fluctuating TIV, and high external hazard risk categories.
6. High review priority does not mean the decline was wrong. It means the record
   resembles historically bound business and should be reviewed as a potential
   missed opportunity.
===============================================================================*/
