Below is the same structured analysis for the **SQM Chile / Sociedad Química y Minera de Chile** NTU case.

---

# SQM Chile — Excel-ready extraction table

| Category                     | Variable / Field to Extract | Value Found in Email / Submission                                                                                        | Why This Matters for NTU                                                             | Possible NTU Reason Signal                   | Confidence  |
| ---------------------------- | --------------------------- | ------------------------------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------------ | -------------------------------------------- | ----------- |
| Account Info                 | Insured Name                | SQM Chile / Sociedad Química y Minera de Chile, S.A.                                                                     | Identifies the account                                                               | Identifier only                              | High        |
| Broker                       | Broker Name                 | Lockton                                                                                                                  | Helps track broker/channel behavior                                                  | Broker / channel analysis                    | High        |
| Market                       | Quoting Market              | Convex                                                                                                                   | Market whose quote became NTU                                                        | Market-level NTU tracking                    | High        |
| Submission Type              | Programme Type              | CAT Only Submission                                                                                                      | Important because quote is limited to CAT layers only                                | CAT-only placement structure                 | High        |
| Inception                    | Inception Date              | 31 July 2025                                                                                                             | Helps renewal timing analysis                                                        | Timing / placement urgency                   | High        |
| Business Description         | Business Activity           | Producer/marketer of specialty plant nutrients, iodine, lithium derivatives, potassium fertilizers, industrial chemicals | Helps understand industrial/mining exposure                                          | Complex industrial risk                      | High        |
| Business Segments            | Business Areas              | Specialty Plant Nutrition; Potassium; Iodine and Derivatives; Lithium and Derivatives; Industrial Chemicals              | Helps classify occupancy/exposure                                                    | Mining/chemical/industrial exposure          | High        |
| ESG / Risk Quality           | ESG / Sustainability        | Carbon footprint, water usage, brine extraction and waste reduction commitments; ISO 14001 mentioned                     | Positive underwriting narrative                                                      | Not NTU reason                               | Medium      |
| Declared Values              | CAT Only TIV                | USD 8,705,437,132                                                                                                        | Very large CAT-only declared value                                                   | Large capacity requirement                   | High        |
| Declared Values              | TIV Change                  | 4.8421% reduction from 2024                                                                                              | Values reduced overall                                                               | Not adverse; positive/neutral                | High        |
| Property Damage              | PD Value                    | USD 6,436,881,253                                                                                                        | Major part of CAT exposure                                                           | Exposure severity                            | High        |
| Property Damage Change       | PD Change                   | Increase of 0.25% from 2024                                                                                              | Small PD increase                                                                    | Neutral / not main NTU reason                | Medium      |
| Business Interruption        | BI Value                    | USD 2,268,555,879                                                                                                        | BI is a major loss driver                                                            | BI accumulation / severity                   | High        |
| Business Interruption Change | BI Change                   | 16.83% decrease, mainly due to reduction in lithium price                                                                | Positive reduction in BI exposure                                                    | Not NTU reason                               | High        |
| Commodity Dependency         | Lithium Price Impact        | Lithium price reduced from 55% of TIV in 2023 renewal to 26% currently                                                   | Values/BI sensitive to lithium price                                                 | Commodity-linked volatility                  | Medium      |
| Loss History                 | 10-Year Loss History        | Excellent for risk size and attachment points                                                                            | Positive risk quality                                                                | Not NTU reason                               | High        |
| Loss History                 | 2014/15                     | Nil                                                                                                                      | Positive                                                                             | Not NTU reason                               | High        |
| Loss History                 | 2015/16                     | Nil                                                                                                                      | Positive                                                                             | Not NTU reason                               | High        |
| Loss History                 | 2016/17                     | Nil                                                                                                                      | Positive                                                                             | Not NTU reason                               | High        |
| Loss History                 | 2017/18                     | Nil                                                                                                                      | Positive                                                                             | Not NTU reason                               | High        |
| Loss History                 | 2018/19                     | USD 246,000 Heavy Rains at Atacama Facility                                                                              | Small historical CAT/weather loss                                                    | Minor loss history signal                    | Medium      |
| Loss History                 | 2019/20 to 2024/25          | Nil                                                                                                                      | Positive loss record                                                                 | Not NTU reason                               | High        |
| Risk Management              | FM Programme                | FM risk management programme set up in 2003                                                                              | Positive risk management factor                                                      | Not NTU reason                               | High        |
| Risk Management              | Loss Ratio / Premium        | Last 20 years losses less than 5% of total premiums paid                                                                 | Strong positive risk quality                                                         | Not NTU reason                               | High        |
| Risk Engineering             | FM Recommendations          | 5 of 6 recommendations completed in iodine facilities; 4 recommendations being reviewed for lithium facilities           | Some ongoing risk improvements                                                       | Minor risk-engineering follow-up             | Medium      |
| Risk Mitigation              | Additional Plants           | SQM invests in additional plants to offset production and reduce BI PML                                                  | Positive BI mitigation                                                               | Not NTU reason                               | Medium-High |
| BI PML                       | BI PML Scenario Change      | Inclusion of SX4 and SX5 makes risk more attractive by reducing BI impact                                                | Positive underwriting factor                                                         | Not NTU reason                               | Medium-High |
| Requested Layer              | Expiring Layer Requested    | USD 200M xs USD 150M                                                                                                     | Broker requested same as prior year                                                  | Original layer need                          | High        |
| Requested Scope              | Perils                      | Flood and Earth Movement only                                                                                            | Very specific CAT-only scope                                                         | Layer/peril structure                        | High        |
| Deductibles / Sublimits      | Programme Deductibles       | Remain as expiring                                                                                                       | Stable terms                                                                         | Not NTU reason                               | Medium      |
| Broker Request               | Alternative Layer Request   | USD 100M xs USD 350M CAT only                                                                                            | Broker later asked for an alternative layer                                          | Structure change / alternative capacity need | High        |
| Broker Request               | Full Stretch Request        | USD 300M xs USD 150M CAT only, or two USD 100M layers top and tail                                                       | Broker explored different layer structures                                           | Layer / structure negotiation                | High        |
| Convex Quote 1               | Initial Convex Quote        | 3% line on USD 200M xs USD 150M @ USD 3.6M less 20%                                                                      | Main Convex quote                                                                    | Price / line size / layer                    | High        |
| Convex Quote 1               | Line Size                   | 3%                                                                                                                       | Small participation                                                                  | Limited capacity                             | High        |
| Convex Quote 1               | Premium                     | USD 3.6M less 20%                                                                                                        | Price basis for original layer                                                       | Pricing signal                               | High        |
| Convex Quote 1               | Quote Conditions            | LTS; T&Cs as expiring; NCG; SNDILR; open 14 days                                                                         | Normal quote conditions                                                              | Not main reason unless disputed              | Medium      |
| Broker Response              | Broker Response to Quote    | “Thank you Matt, will keep you posted”                                                                                   | No acceptance visible                                                                | Outcome uncertainty                          | Medium      |
| Convex Quote 2               | Alternative Layer Quote     | 2% line on USD 100M xs USD 350M @ USD 1.4M less 20%                                                                      | Convex offered alternative layer                                                     | Layer change / smaller participation         | High        |
| Convex Quote 2               | Alternative Line Size       | 2%                                                                                                                       | Very small line                                                                      | Limited capacity / relevance                 | High        |
| Convex Quote 2               | Alternative Premium         | USD 1.4M less 20%                                                                                                        | Alternative pricing basis                                                            | Price signal                                 | High        |
| Convex Quote 2               | Dependency Condition        | To be bound in conjunction with lower layer and not standalone                                                           | Strong restrictive condition                                                         | Tied / non-standalone condition              | High        |
| Convex Quote 2               | All Other Terms             | All else as previously quoted; NCG                                                                                       | Standard continuation                                                                | Quote condition                              | Medium      |
| Placement Flexibility        | Non-Standalone Requirement  | Alternative layer cannot be bound standalone                                                                             | Broker may need flexibility to take only one layer                                   | Restrictive quote condition                  | High        |
| Capacity                     | Total Convex Participation  | 3% original layer; 2% alternative layer                                                                                  | Small participation for very large CAT programme                                     | Capacity / line size mismatch                | High        |
| Final Outcome                | Bound Confirmation          | Not visible in provided chain                                                                                            | Known NTU case but no bind evidence shown                                            | Supports known NTU status, not reason        | Medium      |
| Derived Reason               | Primary NTU Reason          | Restrictive layer / placement condition                                                                                  | Alternative layer was conditional on binding lower layer and not standalone          | Main NTU reason candidate                    | Medium-High |
| Derived Reason               | Secondary NTU Reason 1      | Limited line size                                                                                                        | Convex only offered 3% and 2% lines                                                  | Capacity relevance issue                     | Medium-High |
| Derived Reason               | Secondary NTU Reason 2      | Layer structure mismatch / changing placement need                                                                       | Broker asked for alternative/stretch layers beyond original request                  | Structure complexity                         | Medium      |
| Derived Reason               | Secondary NTU Reason 3      | Price / premium competitiveness                                                                                          | Premiums quoted at USD 3.6M and USD 1.4M less 20%; no direct broker pushback visible | Possible but not clearly evidenced           | Low-Medium  |

---

# Compact Excel-ready version

| Factor                      | Extracted Evidence                                                               | NTU Impact                                                                     | Reason Category               | Confidence |
| --------------------------- | -------------------------------------------------------------------------------- | ------------------------------------------------------------------------------ | ----------------------------- | ---------- |
| Alternative layer requested | Broker asked for USD 100M xs USD 350M CAT only and possibly USD 300M xs USD 150M | Placement need changed from the original requested layer                       | Layer / structure negotiation | High       |
| Original Convex quote       | 3% line on USD 200M xs USD 150M @ USD 3.6M less 20%                              | Convex offered only a small participation on original layer                    | Limited capacity / line size  | High       |
| Alternative Convex quote    | 2% line on USD 100M xs USD 350M @ USD 1.4M less 20%                              | Convex offered an even smaller line on alternative layer                       | Limited capacity / line size  | High       |
| Non-standalone condition    | Alternative layer to be bound in conjunction with lower layer and not standalone | Broker may not have had flexibility to use the alternative quote independently | Restrictive quote condition   | High       |
| CAT-only structure          | Flood and Earth Movement only; CAT-only declared values USD 8.705B               | Large CAT-only programme requires layered capacity                             | CAT placement complexity      | High       |
| Large TIV                   | CAT-only TIV USD 8.705B                                                          | Very large exposure may require meaningful capacity                            | Capacity requirement          | High       |
| Positive loss history       | 10-year loss history excellent; mostly nil losses; only USD 246k heavy rain loss | NTU is unlikely due to poor loss record                                        | Not NTU reason                | High       |
| BI value reduction          | BI reduced by 16.83% mainly due to lithium price reduction                       | Risk profile appears improved, not deteriorated                                | Not NTU reason                | High       |
| Risk management quality     | FM programme since 2003; long-term losses less than 5% of premiums               | Positive underwriting factor                                                   | Not NTU reason                | High       |
| Quote conditions            | LTS, T&Cs as expiring, NCG, SNDILR, open 14 days                                 | Normal quote terms, unless disputed                                            | Low NTU signal                | Medium     |
| No explicit rejection       | Broker only says “will keep you posted”                                          | No clear written rejection reason                                              | Outcome uncertainty           | Medium     |

---

# Final NTU JSON output

```json
{
  "ntu_reason": "Restrictive layer / placement condition",
  "ntu_reason_confidence": "Medium-High",
  "ntu_reason_explanation": "The strongest NTU signal is that Convex's alternative layer quote was not offered standalone. Convex offered a 2% line on the USD 100M xs USD 350M CAT-only layer at USD 1.4M less 20%, but stated that it had to be bound in conjunction with the lower layer and not standalone. Since the broker had specifically asked for alternative/stretch layer options, this restriction may have reduced placement flexibility and made Convex's offer harder to use. The small line sizes of 3% on the original layer and 2% on the alternative layer also suggest limited capacity relevance for a very large CAT-only programme.",
  "secondary_factors": [
    "Limited Convex line size: 3% on USD 200M xs USD 150M and 2% on USD 100M xs USD 350M",
    "Layer structure complexity: broker requested alternative/stretch layers including USD 100M xs USD 350M and possibly USD 300M xs USD 150M",
    "CAT-only programme complexity with USD 8.705B declared CAT values",
    "Price may have been a secondary factor, but there is no direct broker pushback on premium in the visible emails"
  ],
  "do_not_use_as_primary_reason": [
    "Poor loss history",
    "Risk deterioration",
    "BI deterioration",
    "Risk engineering concerns",
    "Material change in risk"
  ]
}
```

# Final quoted reason for Excel

> **Restrictive layer / placement condition — Convex offered the alternative USD 100M xs USD 350M CAT-only layer only if it was bound together with the lower layer and not standalone, while also offering only a small 2% line. This may have reduced broker flexibility and made the quote harder to use in the final placement.**
