CREATE OR REPLACE TABLE OPEN_MARKET_LOSS_FILE_SELECTION_1 (
    RUN_ID STRING,
    ACCOUNT_FOLDER STRING,
    FILE_NAME STRING,
    FILE_PATH STRING,
    FILE_EXTENSION STRING,
    FILE_SIZE NUMBER,
    LAST_MODIFIED STRING,

    LOSS_RELEVANCE_SCORE FLOAT,
    HAS_LOSS_KEYWORD BOOLEAN,
    HAS_CLAIM_KEYWORD BOOLEAN,
    HAS_YEAR_AMOUNT_PATTERN BOOLEAN,
    HAS_TABLE_STRUCTURE BOOLEAN,

    SELECTED_FOR_EXTRACTION BOOLEAN,
    SELECTION_RANK NUMBER,
    SELECTION_REASON STRING,

    PARSE_STATUS STRING,
    ERROR_MESSAGE STRING,

    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE OR REPLACE TABLE OPEN_MARKET_LOSS_HISTORY_EXTRACTION_1 (
    RUN_ID STRING,
    ACCOUNT_FOLDER STRING,
    SOURCE_FILE_NAME STRING,
    SOURCE_FILE_PATH STRING,
    SOURCE_FILE_TYPE STRING,

    LOSS_YEAR NUMBER,
    PERIOD_TEXT STRING,
    POLICY_YEAR_TEXT STRING,
    LOSS_DATE STRING,
    CLAIM_DATE STRING,

    CLAIM_COUNT NUMBER,
    LOSS_AMOUNT FLOAT,
    CURRENCY STRING,
    CURRENCY_SOURCE STRING,
    AMOUNT_TYPE STRING,

    PAID_AMOUNT FLOAT,
    OUTSTANDING_AMOUNT FLOAT,
    INCURRED_AMOUNT FLOAT,
    REINSURER_PAYOUT FLOAT,
    TOTAL_PAYABLE_BY_REINSURERS FLOAT,
    AGGREGATE_EROSION FLOAT,

    IS_INDIVIDUAL_CLAIM_ROW BOOLEAN,
    IS_YEAR_SUMMARY_ROW BOOLEAN,
    IS_TOTAL_OR_SUBTOTAL_ROW BOOLEAN,
    EXCLUDE_FROM_AGGREGATION BOOLEAN,

    SOURCE_SHEET_NAME STRING,
    SOURCE_PAGE_NUMBER NUMBER,
    SOURCE_SECTION_NAME STRING,
    SOURCE_ROW_TEXT STRING,

    CONFIDENCE FLOAT,
    EXTRACTION_REASON STRING,

    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE OR REPLACE TABLE OPEN_MARKET_LOSS_HISTORY_AGGREGATED_1 (
    RUN_ID STRING,
    ACCOUNT_FOLDER STRING,

    MIN_LOSS_YEAR NUMBER,
    MAX_LOSS_YEAR NUMBER,
    AVAILABLE_LOSS_YEAR_COUNT NUMBER,

    TOTAL_AVAILABLE_CLAIM_COUNT NUMBER,
    TOTAL_AVAILABLE_LOSS_AMOUNT FLOAT,

    LAST_10_YEAR_CLAIM_COUNT NUMBER,
    LAST_10_YEAR_LOSS_AMOUNT FLOAT,

    CURRENCY STRING,
    DATA_QUALITY_FLAG STRING,
    AGGREGATION_REASON STRING,

    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
