CREATE OR REPLACE TABLE OPEN_MARKET_LOSS_FILE_SELECTION_4 (
    RUN_ID STRING,
    ACCOUNT_FOLDER STRING,
    FILE_NAME STRING,
    FILE_PATH STRING,
    FILE_EXTENSION STRING,
    FILE_SIZE NUMBER,
    LAST_MODIFIED STRING,

    LOSS_RELEVANCE_SCORE FLOAT,
    CONTENT_LOSS_FOUND BOOLEAN,
    SELECTED_FOR_EXTRACTION BOOLEAN,
    ATTEMPTED_EXTRACTION BOOLEAN,
    EXTRACTION_ROW_COUNT NUMBER,

    SELECTION_RANK NUMBER,
    SELECTION_REASON STRING,
    PARSE_STATUS STRING,
    ERROR_MESSAGE STRING,

    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE OPEN_MARKET_LOSS_HISTORY_EXTRACTION_4 (
    RUN_ID STRING,
    ACCOUNT_FOLDER STRING,
    SOURCE_FILE_NAME STRING,
    SOURCE_FILE_PATH STRING,
    SOURCE_FILE_TYPE STRING,

    LOSS_YEAR NUMBER,
    PERIOD_TEXT STRING,
    LOSS_DATE STRING,

    CLAIM_COUNT FLOAT,
    LOSS_AMOUNT FLOAT,
    CURRENCY STRING,
    AMOUNT_TYPE STRING,

    SOURCE_SHEET_NAME STRING,
    SOURCE_ROW_TEXT STRING,

    INCLUDE_IN_AGGREGATION BOOLEAN,
    CONFIDENCE FLOAT,
    EXTRACTION_REASON STRING,

    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE OPEN_MARKET_LOSS_HISTORY_AGGREGATED_4 (
    RUN_ID STRING,
    ACCOUNT_FOLDER STRING,

    MIN_LOSS_YEAR NUMBER,
    MAX_LOSS_YEAR NUMBER,
    AVAILABLE_LOSS_YEAR_COUNT NUMBER,

    TOTAL_AVAILABLE_CLAIM_COUNT FLOAT,
    TOTAL_AVAILABLE_LOSS_AMOUNT FLOAT,

    LAST_10_YEAR_CLAIM_COUNT FLOAT,
    LAST_10_YEAR_LOSS_AMOUNT FLOAT,

    CURRENCY STRING,
    DATA_QUALITY_FLAG STRING,
    AGGREGATION_REASON STRING,

    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE OPEN_MARKET_LOSS_PROCESSED_ACCOUNTS_4 (
    ACCOUNT_FOLDER STRING,
    LAST_RUN_ID STRING,
    STATUS STRING,
    PROCESSED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    ERROR_MESSAGE STRING
);
