CREATE DATABASE IF NOT EXISTS EXPERIMENT_TEAM_DB;
CREATE SCHEMA IF NOT EXISTS EXPERIMENT_TEAM_DB.PUBLIC;

USE DATABASE EXPERIMENT_TEAM_DB;
USE SCHEMA PUBLIC;





CREATE OR REPLACE STAGE TEST_A
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
  DIRECTORY = (ENABLE = TRUE);







CREATE OR REPLACE TABLE EXTRACTED_INSURANCE_SUBMISSIONS (
    FILE_NAME STRING,
    FILE_TYPE STRING,
    STATUS STRING,
    INSURED_NAME STRING,
    PROPERTY_ADDRESSES STRING,
    BUILDING_REAL_PROPERTY_VALUE STRING,
    BUSINESS_PERSONAL_PROPERTY_VALUE STRING,
    BUSINESS_INCOME_VALUE STRING,
    TOTAL_INSURABLE_VALUE STRING,
    REASON STRING,
    EXTRACTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
