SELECT
    SPLIT_PART(RELATIVE_PATH, '/', 2) AS ACCOUNT_FOLDER,
    COUNT(*) AS FILE_COUNT,
    LISTAGG(SPLIT_PART(RELATIVE_PATH, '/', -1), ', ') 
        WITHIN GROUP (ORDER BY RELATIVE_PATH) AS FILE_NAMES
FROM DIRECTORY(@OPEN_MARKET_QUOTE)
WHERE RELATIVE_PATH ILIKE 'Open_Market/%'
  AND REGEXP_LIKE(RELATIVE_PATH, '.*[.](pdf|png|jpg|jpeg|doc|docx)$', 'i')
  AND ARRAY_SIZE(SPLIT(RELATIVE_PATH, '/')) >= 3
GROUP BY SPLIT_PART(RELATIVE_PATH, '/', 2)
ORDER BY FILE_COUNT DESC;
