USE DATABASE EXPERIMENT_TEAM_DB;
USE SCHEMA PUBLIC;

CREATE OR REPLACE TABLE INSURED_SUBMISSION_EXTRACTED_VALUES (
    INSURED_NAME STRING,
    SUBMISSION_YEAR STRING,

    TIV_BASED_ON_AVG_INVENTORY NUMBER(38,2),
    TIV_SOURCE_FILE STRING,

    TOTAL_NET_PAID_LOSS NUMBER(38,2),
    LOSS_YEARS NUMBER,
    LOSS_SOURCE_FILE STRING,

    ALL_PROCESSED_FILES ARRAY,
    EXTRACTION_STATUS STRING,
    ERROR_MESSAGE STRING,

    PROCESSED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CALL PROCESS_OPEN_MARKET_SUBMISSIONS_XLSX();



LIST @EXPERIMENT_TEAM_DB.PUBLIC.DROPBOX_STAGE
PATTERN = '.*Open Market.*/202[4-6][^/]*/submission/.*[.][xX][lL][sS][xX]$';
