SHOW PROCEDURES LIKE 'PARSE_FILE_IF_NEEDED' IN SCHEMA EXPERIMENT_TEAM_DB.PUBLIC;
SHOW PROCEDURES LIKE 'EXTRACT_FILE_FIELDS' IN SCHEMA EXPERIMENT_TEAM_DB.PUBLIC;
SHOW PROCEDURES LIKE 'RUN_DOCUMENT_EXTRACTION_PIPELINE' IN SCHEMA EXPERIMENT_TEAM_DB.PUBLIC;

TRUNCATE TABLE EXPERIMENT_TEAM_DB.PUBLIC.EXTRACTED_INSURANCE_SUBMISSIONS;

CALL EXPERIMENT_TEAM_DB.PUBLIC.RUN_DOCUMENT_EXTRACTION_PIPELINE();

SELECT *
FROM EXPERIMENT_TEAM_DB.PUBLIC.EXTRACTED_INSURANCE_SUBMISSIONS
ORDER BY EXTRACTED_AT DESC;
